# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 534f7bf8a3338a518b75e65b5b220847580c46be95e5121c3e8104c95f3bc9a00f9bc7aa3c1826e58387b57d94c12ba4956f33a6bd2eca1ae2c64aac84a63a25

test:
  secret_key_base: e0854ba8b0b04315f1add233bbf7113370f8672665b0a984cd9c92fe799ece975e0b2bea3a2e978a0b878d6512e395d7c692ee4637399b758075e09fd28dfa82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
